name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Running all tests
      run: |
        cd tests
        tests=$(find . -name "*.c")
        for test in $tests; do
            echo $test
            gcc ../src/biblio.c $test
            ./a.out
            rm -rf a.out
        done;
